### ISSUE TITLE
Empty report fails

### ISSUE THREAD

**Issue by bethebunny** [bethebunny/kepler#2]
Repro:
```python
import kepler
kepler.report()
```
Error:
```
Traceback (most recent call last):
  File "/home/stef/kepler/empty_report_test.py", line 2, in <module>
    kepler.report()
  File "/home/stef/kepler/kepler/timer.py", line 153, in report
    reporter.report(current_context())
  File "/home/stef/kepler/kepler/reporting.py", line 196, in report
    min(min(event.times) for event in events if event.times),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() iterable argument is empty
```

**Comment by bethebunny** [comment]
It's probably sensible for this to fail, but it now does so intentionally and raises a `ValueError`.
